# Generated by Django 5.0.6 on 2026-03-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_service", "0002_appointment_appointment_type_and_more"),
        ("ehr_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ehr_prescription",
                to="appointments_service.appointment",
            ),
        ),
    ]
