# Generated by Django 5.0.6 on 2026-03-14 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab_reports_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labreport",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RenameField(
            model_name="labreport",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RenameField(
            model_name="labreport",
            old_name="patient",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="test_date",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="labreport",
            name="uploaded_by",
        ),
        migrations.AddField(
            model_name="labreport",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labreport",
            name="ai_structured_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labreport",
            name="extracted_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labreport",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lab_reports/"),
        ),
        migrations.AddField(
            model_name="labreport",
            name="ocr_raw_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labreport",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("blood_test", "Blood Test"),
                    ("urine_test", "Urine Test"),
                    ("lipid_panel", "Lipid Panel"),
                    ("liver_function", "Liver Function Test"),
                    ("kidney_function", "Kidney Function Test"),
                    ("thyroid", "Thyroid Panel"),
                    ("cbc", "Complete Blood Count"),
                    ("diabetes", "Diabetes Panel"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="labreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="labreport",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name="labreport",
            table=None,
        ),
        migrations.CreateModel(
            name="ReportQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, null=True)),
                ("asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="lab_reports_service.labreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asked_at"],
            },
        ),
        migrations.DeleteModel(
            name="LabTestResult",
        ),
    ]
