# Generated by Django 5.0.6 on 2026-03-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("total_beds", models.PositiveIntegerField(default=0)),
                ("available_beds", models.PositiveIntegerField(default=0)),
                ("icu_total", models.PositiveIntegerField(default=0)),
                ("icu_available", models.PositiveIntegerField(default=0)),
                ("emergency_beds", models.PositiveIntegerField(default=0)),
                ("emergency_available", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "hospital"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CapacityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_beds", models.PositiveIntegerField()),
                ("available_beds", models.PositiveIntegerField()),
                ("icu_total", models.PositiveIntegerField()),
                ("icu_available", models.PositiveIntegerField()),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_logs",
                        to="hospital_service.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "capacity_logs",
                "ordering": ["-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="hospital_service.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "hospital_amenities",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("head_doctor_name", models.CharField(blank=True, max_length=200)),
                ("phone_extension", models.CharField(blank=True, max_length=20)),
                ("floor", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="hospital_service.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "hospital_departments",
                "unique_together": {("hospital", "name")},
            },
        ),
    ]
